### ISSUE TITLE
Launching as Deamon?

### ISSUE THREAD

**Issue by Preen** [ilons/newrelic_varnish_plugin#4]
Hi
Is it possible to launch this deamonized?

**Comment by ilons** [comment]
Yes, it is possible to run it as a daemon, I'll upload an example for Debian (which is the distribution I often use).

**Comment by ilons** [comment]
Does the daemon script in [d74965efca709879c19028415667aff836b2981c](https://github.com/ilons/newrelic_varnish_plugin/commit/d74965efca709879c19028415667aff836b2981c) work for you?

**Comment by s-hoffman** [comment]
Do you have a version for CentOS/RHEL?

**Comment by ilons** [comment]
No, I don't have one for CentOS/RHEL at the moment.
